#!/usr/bin/env python3

if __name__ == '__main__':
    
    #Creates the board
    board = {'top-L': ' ', 'top-M': ' ', 'top-R': ' ',
                'mid-L': ' ', 'mid-M': ' ', 'mid-R': ' ',
                'low-L': ' ', 'low-M': ' ', 'low-R': ' '}
    def print_board(board):
        print(board['top-L'] + '|' + board['top-M'] + '|' + board['top-R'])
        print('-+-+-')
        print(board['mid-L'] + '|' + board['mid-M'] + '|' + board['mid-R'])
        print('-+-+-')
        print(board['low-L'] + '|' + board['low-M'] + '|' + board['low-R'])
        
    #Function to quit
    def end(move):
        if move == 'quit':
            raise SystemExit
        
    #Function to check if any player has won
    def check_board(board, turn):
        win_conditions = [
             ['top-L', 'mid-L', 'low-L'],
             ['top-M', 'mid-M', 'low-M'],
             ['top-R', 'mid-R', 'low-R'],
             ['top-L', 'top-M', 'top-R'],
             ['mid-L', 'mid-M', 'mid-R'],
             ['low-L', 'low-M', 'low-R'],
             ['top-L', 'mid-M', 'low-R'],
             ['top-R', 'mid-M', 'low-L']]
        for condition in win_conditions:
            if (board[condition[0]] != ' ' and board[condition[0]] == board[condition[1]] == board[condition[2]]):
                print_board(board)
                print(turn + ' wins!\n')
                print('Would you like to play again? Type yes to play again.\n')
                answer = input()
                if answer == 'yes':
                    return answer
                else:
                    raise SystemExit
    turn = 'X'
    move = ' '
    print('Type in "quit" to end game.')
    print('\nTo choose a position, type in which row(top, mid, low) followed by which column(-R, -M, -L')
    print('To move to the top left corner, you would type "top-L", bottom mid would be "low-M", without the quotes.')
    
    #Loop where the game exists
    while move != 'quit':
        print_board(board)
        print('Turn for ' + turn + '. Move on which space?')
        move = input()
        end(move)
        if (move not in board):
            print('\nTry again.')
            continue
        elif (board[move] == ' '):
            board[move] = turn
        else:
            print('\nTry again.')
            continue
        if (check_board(board, turn) == 'yes'):
            board = board.fromkeys(board, ' ')
            continue
        check_board(board, turn)
        if turn == 'X':
            turn = 'O'
        else:
            turn = 'X'
      

        
        

